theme: jekyll-theme-cayman
title: React Redux Starter Kit by Nisarg Thakkar
slogan: "Best React Redux Starter Kit"
description: "React Redux Starter Kit is which let's you build rich real world apps. It's not as light as some starter kits which only let you write a simple hello world app and then you have to struggle with installing all the other stuff yourself."
author: Nisarg R Thakkar
improve_content: https://github.com/nisargrthakkar/react-redux-starter-kit/issues
whitelist:
  - jekyll-sitemap
  - jekyll-seo-tag
  
google_author:"https://plus.google.com/u/1/+NisargThakkar113"
og_image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png"
og_locale:"en_EN"
og_type:"website"
og_title:"React Redux Starter Kit by Nisarg Thakkar"
og_description:"React Redux Starter Kit is which let's you build rich real world apps. It's not as light as some starter kits which only let you write a simple hello world app and then you have to struggle with installing all the other stuff yourself."
keywords: "React, Redux , Starter Kit , Webpack, Babel, material-ui, Eslint , "
twitter_image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png"
twitter_locale:"en_EN"
twitter_type:"website"
twitter_title:"React Redux Starter Kit by Nisarg Thakkar"
twitter_description:"React Redux Starter Kit is which let's you build rich real world apps. It's not as light as some starter kits which only let you write a simple hello world app and then you have to struggle with installing all the other stuff yourself."
